name: 01 Github Actions Demo

on:
  push: 
    branches: [main]

jobs:
  EXPLORE-gh-ACTIONS:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event"
      - run: echo "Job  triggered in a ${{ runner.os }} server hosted by GH"
      - name: checkout repo
        uses: actions/checkout@v3

      - run: |
          ls ${{ github. workspace }}
          echo " files listed "
          
  
