name: 05-3 Hello world Docker

on:
  workflow_dispatch
  
jobs:
  hello-world-docker:
    runs-on: ubuntu-latest 
    name: A job to hello
    steps:
      - uses: actions/checkout@v3
      
      - name: hello-world
        uses: ./.github/actions/hello-world-docker
      
