name: 05-4 Hello world JS

on:
  workflow_dispatch
  
jobs:
  hello-world-js:
    runs-on: ubuntu-latest 
    name: A job to hello
    steps:
      - uses: actions/checkout@v3
      
      - name: hello-world
        uses: ./.github/actions/hello-world-js
      
