name: 02- Simple Workflow

on:
   
  workflow_dispatch:
  
jobs:
  build:
    name: Build simple workflow
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          
      - name: display path
        run: echo ${env:PATH}
        shell: pwsh
        
      - name: display path
        run: echo ${env:PATH}
        shell: bash


     



              


